# tokens.awk -- BODIES -> which model a repository can be made to talk to.
#
# Input : a `git cat-file --batch` stream on stdin, plus -v map=<file>
#         holding "<sha>\t<kind>\t<path>" lines from select.awk.
# Output: one line, tab separated:
#         read  anom  local  broker  override  hosted  prose  selfname
#         where the last six are comma-joined family lists ("-" when empty).
#
# ---------------------------------------------------------------------------
# P113-E  THE BATCH STREAM IS PARSED BY BYTE COUNT, NOT BY PATTERN. p112 (and
#   p111 before it) dropped `git cat-file --batch` headers on an anchored
#   40-hex pattern, which is a HEURISTIC: a blob whose own content holds a line
#   matching that shape is read as a header, and from there every following
#   line is attributed to the wrong file. The header carries the exact payload
#   size, so this instrument consumes that many bytes and only then expects the
#   next header. A content line shaped like a header is therefore consumed AS
#   CONTENT, which is what it is. Git emits one extra newline after each
#   payload; that separator is consumed explicitly, and any line arriving
#   outside a record is counted in `anom` rather than silently classified --
#   P1040's rule, that a silence is never data, applied to the parser itself.
#
# P113-F  CONTAINMENT IS THE DEFAULT FAILURE OF TOKEN MATCHING ON THIS SHELF,
#   SO MATCHING IS ORDERED REMOVAL. `openai-whisper` is a LOCAL inference
#   package and contains `openai`. `sentence-transformers` contains
#   `transformers`. `OPENAI_API_BASE` is an endpoint OVERRIDE and contains
#   `openai`. `langchain-openai` is a BROKER binding and contains both. The
#   classifier walks an ordered table, most specific first, and ERASES every
#   token it matches from the line before the next test runs, so no shorter
#   token can ever harvest a longer one's text. This is the exact fault p1040
#   found in its own licence classifier ("Educational Community License"
#   contains "Community License"); it is pre-empted here and tested against
#   real payloads in test_p113.sh.
#
# P113-G  A GENERIC ENDPOINT NAME IS ONLY EVIDENCE NEXT TO A MODEL. `base_url`
#   and `api_base` name an override in an LLM client and a web host in
#   everything else. They are credited ONLY when the SAME FILE also names a
#   hosted provider or a local runtime. Tokens that name the thing themselves
#   -- `openai_api_base`, `openai-compatible`, `llm_endpoint` -- need no
#   companion and are credited repo-wide.
#
# P113-Q  A TOKEN FLANKED BY AN ALPHANUMERIC IS PART OF A LONGER WORD AND IS
#   NOT THE TOKEN. Substring matching alone produced four false positives on
#   the first full run of this shelf, every one of them read off a real payload
#   and every one of them a different cause:
#     `apache/ofbiz-framework`  "one coherent run"              -> cohere
#     `ls1intum/Artemis`        "autogenerated by uv"           -> autogen
#     `temporalio/temporal`     "bedrockagentcore v1.36.4"      -> bedrock
#   and `replicate` is an ordinary English verb besides. The Artemis one CHANGED
#   A VERDICT: a uv lockfile's header comment promoted an LMS to `broker`. So
#   every token is matched with a non-alphanumeric required on both sides. The
#   line is padded with a space at each end so no anchor is needed, and the
#   replacement is a space, which keeps the boundary intact for the tokens that
#   follow -- `litellm,openai` must still yield both. P1040's lesson in its own
#   costume: the containment bug is the default, not the exception.
#
# P113-R  A PROVIDER NAME THAT IS ALSO THE REPOSITORY'S OWN NAME IS FLAGGED AND
#   NEVER SUPPRESSED, BECAUSE NO RULE CAN SEPARATE THE TWO CASES.
#     `aiverify-foundation/moonshot` is Singapore's LLM red-teaming toolkit. Its
#       own manifests carry the name `moonshot`, which is also a Chinese model
#       vendor. It binds to neither.
#     `nextcloud/integration_openai` carries `openai` in its own name too -- and
#       it is the OpenAI integration for Nextcloud. The name IS the binding.
#   A name-based suppression would be right on the first and wrong on the
#   second, so this instrument refuses to decide: the colliding families go in
#   a `selfname` column, the verdict is left standing, and the affected rows are
#   adjudicated BY HAND in the prose with the payload named. p93 settled this
#   policy already -- declining to classify is the correct failure mode, and
#   forking the classifier to get a nicer number is the one P237 forbids.
#
# P113-H  AN AGGREGATOR IS SUBSTITUTABLE AND IS NOT EGRESS-FREE. OpenRouter and
#   Portkey make the model swappable by configuration, which is what `broker`
#   asserts, and they are still somebody else's endpoint. The verdict says
#   substitutable; the family list says who, so a reader sorting for data
#   residency can see `openrouter` and discount it. The verdict is never
#   allowed to imply sovereignty on its own.
# ---------------------------------------------------------------------------
BEGIN {
  # NOTE: default FS. The batch header "<sha> blob <size>" is SPACE separated;
  # setting FS to tab here (the map file is split explicitly below) silently made
  # $3 empty, so every payload size read as 0 and every content line landed in
  # `anom`. Found by the smoke test before the suite existed.
  
  while ((getline m < map) > 0) {
    split(m, f, "\t")
    if (f[1] != "" && f[1] !~ /^#/) kindof[f[1]] = f[2]
  }
  close(map)
  n = 0
  # class: L local, O override (specific), B broker, H hosted
  t[++n]="sentence-transformers|L|sentence-transformers"
  t[++n]="sentence_transformers|L|sentence-transformers"
  t[++n]="openai-whisper|L|whisper-local"
  t[++n]="faster-whisper|L|whisper-local"
  t[++n]="whisper.cpp|L|whisper-local"
  t[++n]="whisper-cpp|L|whisper-local"
  t[++n]="llama-cpp|L|llama.cpp"
  t[++n]="llama_cpp|L|llama.cpp"
  t[++n]="llama.cpp|L|llama.cpp"
  t[++n]="text-generation-inference|L|tgi"
  t[++n]="text-generation-webui|L|tg-webui"
  t[++n]="ctransformers|L|ctransformers"
  t[++n]="gpt4all|L|gpt4all"
  t[++n]="localai|L|localai"
  t[++n]="local-ai|L|localai"
  t[++n]="mlx-lm|L|mlx"
  t[++n]="mlx_lm|L|mlx"
  t[++n]="exllama|L|exllama"
  t[++n]="sglang|L|sglang"
  t[++n]="unsloth|L|unsloth"
  t[++n]="vllm|L|vllm"
  t[++n]="ollama|L|ollama"
  t[++n]="lm-studio|L|lmstudio"
  t[++n]="lmstudio|L|lmstudio"
  t[++n]="modelfile|L|modelfile"
  t[++n]="sentencepiece|L|hf-local"
  t[++n]="transformers|L|transformers"
  t[++n]="whisper|L|whisper-local"
  # specific overrides, ahead of every hosted token they contain (P113-F)
  t[++n]="openai_api_base|O|openai-api-base"
  t[++n]="openai-api-base|O|openai-api-base"
  t[++n]="openai_base_url|O|openai-base-url"
  t[++n]="openai-base-url|O|openai-base-url"
  t[++n]="openai_api_host|O|openai-api-host"
  t[++n]="openai-compatible|O|openai-compatible"
  t[++n]="openai_compatible|O|openai-compatible"
  t[++n]="llm_endpoint|O|llm-endpoint"
  t[++n]="llm_base_url|O|llm-base-url"
  t[++n]="llm_api_base|O|llm-api-base"
  t[++n]="inference_endpoint|O|inference-endpoint"
  t[++n]="model_endpoint|O|model-endpoint"
  # brokers, ahead of hosted so `langchain-openai` yields BOTH (P113-F)
  t[++n]="litellm|B|litellm"
  t[++n]="langchain|B|langchain"
  t[++n]="llama-index|B|llama-index"
  t[++n]="llama_index|B|llama-index"
  t[++n]="llamaindex|B|llama-index"
  t[++n]="haystack|B|haystack"
  t[++n]="semantic-kernel|B|semantic-kernel"
  t[++n]="semantic_kernel|B|semantic-kernel"
  t[++n]="pydantic-ai|B|pydantic-ai"
  t[++n]="pydantic_ai|B|pydantic-ai"
  t[++n]="aisuite|B|aisuite"
  t[++n]="openrouter|B|openrouter"
  t[++n]="portkey|B|portkey"
  t[++n]="dspy|B|dspy"
  t[++n]="crewai|B|crewai"
  t[++n]="crew-ai|B|crewai"
  # P113-S  A FRAMEWORK'S NAME IS NOT ITS DISTRIBUTION NAME, AND THE BARE WORD
  #   IS A FILENAME. `autogen` passed P113-Q's boundary test inside
  #   `autogen.js` -- a dot is not alphanumeric -- and promoted
  #   `GibbonEdu/core`, a PHP school platform, to `broker` on the strength of a
  #   test-script name in a VENDORED copy of Chart.js under `lib/`. Two faults
  #   compounding: a generic word used as a token, and a third-party tree that
  #   is not called `node_modules`. The root fix is the first one: AutoGen does
  #   not ship as `autogen`, it ships as `pyautogen`, `autogen-core`,
  #   `autogen-agentchat`, `autogen-ext` and `autogenstudio`, so those are the
  #   tokens and the bare word is gone. Chasing the extension instead would
  #   have left the generic word in the table for the next filename to catch.
  t[++n]="pyautogen|B|autogen"
  t[++n]="autogen-core|B|autogen"
  t[++n]="autogen_core|B|autogen"
  t[++n]="autogen-agentchat|B|autogen"
  t[++n]="autogen_agentchat|B|autogen"
  t[++n]="autogen-ext|B|autogen"
  t[++n]="autogenstudio|B|autogen"
  t[++n]="langroid|B|langroid"
  t[++n]="griptape|B|griptape"
  t[++n]="mirascope|B|mirascope"
  t[++n]="smolagents|B|smolagents"
  t[++n]="agno|B|agno"
  # hosted
  t[++n]="azure-openai|H|azure-openai"
  t[++n]="azure_openai|H|azure-openai"
  t[++n]="azure-ai-inference|H|azure-ai"
  t[++n]="google-generativeai|H|google"
  t[++n]="google_generativeai|H|google"
  t[++n]="google-genai|H|google"
  t[++n]="google_genai|H|google"
  t[++n]="generativeai|H|google"
  t[++n]="vertexai|H|vertex"
  t[++n]="vertex-ai|H|vertex"
  t[++n]="gemini|H|gemini"
  t[++n]="openai|H|openai"
  t[++n]="anthropic|H|anthropic"
  t[++n]="cohere|H|cohere"
  t[++n]="mistralai|H|mistral"
  t[++n]="mistral-ai|H|mistral"
  t[++n]="groq|H|groq"
  t[++n]="replicate|H|replicate"
  t[++n]="bedrock|H|bedrock"
  t[++n]="deepseek|H|deepseek"
  t[++n]="dashscope|H|dashscope"
  t[++n]="qianfan|H|qianfan"
  t[++n]="zhipu|H|zhipu"
  t[++n]="moonshot|H|moonshot"
  t[++n]="togetherai|H|together"
  t[++n]="together-ai|H|together"
  t[++n]="fireworks-ai|H|fireworks"
  t[++n]="perplexity|H|perplexity"
  ntok = n
  for (i = 1; i <= ntok; i++) {
    split(t[i], p, "|"); tok[i] = p[1]; cls[i] = p[2]; fam[i] = p[3]
    e = tok[i]; gsub(/\./, "\\.", e)                       # P113-Q: `llama.cpp`
    rex[i] = "[^a-z0-9]" e "[^a-z0-9]"
  }
  # P113-R: the repository's own name, split the way a manifest spells it.
  nself = split(tolower(slug), sp, /[\/_.-]/)
  for (i = 1; i <= nself; i++) if (sp[i] != "") selfname[sp[i]] = 1
  want = 0; sep = 0
}

# ---- P113-E: byte-exact record framing ------------------------------------
# P113-M  THE RECORD SEPARATOR IS OPTIONAL, BECAUSE NOT EVERY FILE ENDS IN A
#   NEWLINE. Git writes <payload> then one newline. When the payload already
#   ends in a newline that shows up as a BLANK line; when it does not, git's
#   newline merely terminates the last content line and NO blank line follows.
#   Consuming a separator unconditionally therefore eats the next HEADER on
#   every file with no trailing newline, and from that point every line is
#   attributed to the wrong file -- one missing byte desynchronises the whole
#   stream. Measured, not reasoned: `learningequality/kolibri` reported 47 of
#   59 files read and 474 stray lines until this was fixed. So the separator is
#   consumed ONLY when it is actually blank, and otherwise the same line is
#   handed on to the header rule.
want == 0 && sep == 1 {
  sep = 0
  if ($0 == "") next
  # not blank: fall through, this is the next header
}
want == 0 && /^[0-9a-f]{40} blob [0-9]+$/ {
  flush()
  cur = kindof[$1]; if (cur == "") cur = "unmapped"
  want = $3 + 0; used = 0
  if (want == 0) { sep = 1 }
  read++
  next
}
want == 0 && /^[0-9a-f]{40} (missing|ambiguous)/ { miss++; next }
want == 0 { anom++; next }                   # a line nobody asked for (P1040)

{
  used += length($0) + 1
  scan($0)
  if (used >= want) { want = 0; sep = 1 }
  next
}

function scan(line,   s, i, f, hostedhere, localhere) {
  s = " " tolower(line) " "          # P113-Q: padded, so no anchor is needed
  # P113-F: ordered removal. Longest/most specific token wins its text.
  for (i = 1; i <= ntok; i++) {
    if (match(s, rex[i]) > 0) {
      gsub(rex[i], " ", s)           # P113-Q: a space keeps the next boundary
      f = fam[i]
      # P113-R: FLAG, never suppress. The first cut of this code `continue`d
      # here, and `nextcloud/integration_openai` -- which is genuinely the
      # OpenAI integration for Nextcloud -- lost its only binding and dropped
      # to `no-model`. The collision is recorded alongside the verdict, and a
      # human adjudicates it; the verdict itself is left exactly as the payload
      # dictates.
      if (cls[i] == "H" && (tok[i] in selfname)) rs[f] = 1
      if (cls[i] == "L") { rl[f] = 1; localhere = 1 }
      if (cls[i] == "O")   ro[f] = 1
      if (cls[i] == "B")   rb[f] = 1
      if (cls[i] == "H") { rh[f] = 1; hostedhere = 1 }
    }
  }
  if (hostedhere || localhere) recmodel = 1          # companion for P113-G
  if (index(s, "base_url") > 0 || index(s, "api_base") > 0) recgeneric = 1
}

# Merge one file's findings into the repository's, applying P113-G and P113-A.
function flush(   f) {
  if (cur == "") return
  if (recgeneric && recmodel) ro["base-url"] = 1                      # P113-G
  if (cur == "readme") {                                              # P113-A
    for (f in rl) prose[f] = 1
    for (f in rb) prose[f] = 1
    for (f in ro) prose[f] = 1
    for (f in rh) prose[f] = 1
    for (f in rs) prose[f] = 1
  } else {
    for (f in rl) L[f] = 1
    for (f in rb) B[f] = 1
    for (f in ro) O[f] = 1
    for (f in rh) H[f] = 1
    for (f in rs) S[f] = 1
  }
  delete rl; delete rb; delete ro; delete rh; delete rs
  recmodel = 0; recgeneric = 0; cur = ""
}

function join(a,   k, out, m, i, j, tmp) {
  m = 0
  for (k in a) tmp[++m] = k
  if (m == 0) return "-"
  for (i = 2; i <= m; i++) { k = tmp[i]; for (j = i - 1; j >= 1 && tmp[j] > k; j--) tmp[j+1] = tmp[j]; tmp[j+1] = k }
  out = tmp[1]
  for (i = 2; i <= m; i++) out = out "," tmp[i]
  return out
}

END {
  flush()
  printf "%d\t%d\t%s\t%s\t%s\t%s\t%s\t%s\n", read + 0, anom + 0, \
    join(L), join(B), join(O), join(H), join(prose), join(S)
}
